import React, { useState, useEffect } from 'react';
import { useAuth } from '../../context/AuthContext';
import { useLanguage } from '../../context/LanguageContext';
import { db } from '../../db/database';
import { SystemBackupRecord } from '../../types';
import { createEncryptedBackup, restoreEncryptedBackup } from '../../services/backupService';
import { sendPhoneSmsAlert, DEFAULT_UNIT_PHONE } from '../../services/smsService';
import { 
  Database, Download, Upload, ShieldCheck, 
  Lock, AlertTriangle, CheckCircle2, Clock 
} from 'lucide-react';

export const BackupRestoreModule: React.FC = () => {
  const { currentUser } = useAuth();
  const { t, formatNumber } = useLanguage();

  const [backups, setBackups] = useState<SystemBackupRecord[]>([]);
  const [isGenerating, setIsGenerating] = useState<boolean>(false);
  const [restoreFile, setRestoreFile] = useState<File | null>(null);
  const [restorePassphrase, setRestorePassphrase] = useState<string>('UNIT-READY-360-SECURE-KEY');
  const [restoreMessage, setRestoreMessage] = useState<string | null>(null);

  const loadBackups = async () => {
    const list = await db.backups.toArray();
    setBackups(list.sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()));
  };

  useEffect(() => {
    loadBackups();
  }, []);

  const handleCreateBackup = async () => {
    setIsGenerating(true);
    try {
      const { filename, blob } = await createEncryptedBackup(currentUser, restorePassphrase);
      
      // Trigger browser download
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = filename;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);

      // Dispatch Phone SMS Alert
      await sendPhoneSmsAlert(
        'System Backup Created',
        `Encrypted archive ${filename} generated by ${currentUser.appointmentTitle}. AES-GCM-256 verified.`,
        'SYSTEM',
        currentUser.appointmentTitle,
        DEFAULT_UNIT_PHONE
      );

      alert(`Backup created successfully: ${filename}`);
      loadBackups();
    } catch (err: any) {
      alert(`Backup creation failed: ${err.message}`);
    } finally {
      setIsGenerating(false);
    }
  };

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      setRestoreFile(e.target.files[0]);
    }
  };

  const handleExecuteRestore = async () => {
    if (!restoreFile) {
      alert('Please select an encrypted backup archive file (.bak).');
      return;
    }

    try {
      const text = await restoreFile.text();
      const backupRecord: SystemBackupRecord = JSON.parse(text);

      const result = await restoreEncryptedBackup(currentUser, backupRecord, restorePassphrase);
      if (result.success) {
        setRestoreMessage(`SUCCESS: ${result.message} Total records restored: ${result.recordCount}`);
        alert('System state restored and verified successfully. Reloading application...');
        window.location.reload();
      } else {
        setRestoreMessage(`FAILED: ${result.message}`);
        alert(`Restore Error: ${result.message}`);
      }
    } catch (err: any) {
      alert(`Invalid backup file structure: ${err.message}`);
    }
  };

  const isCoOrAdmin = currentUser.role === 'co' || currentUser.role === 'admin';
  const [lastSyncTime, setLastSyncTime] = useState<string>(new Date().toLocaleString());

  useEffect(() => {
    const handleSync = () => {
      setLastSyncTime(new Date().toLocaleString());
    };
    window.addEventListener('unit-ready-cloud-sync', handleSync);
    return () => window.removeEventListener('unit-ready-cloud-sync', handleSync);
  }, []);

  if (!isCoOrAdmin) {
    return (
      <div className="bg-amber-50 dark:bg-amber-950/40 border-2 border-amber-500 rounded-xl p-8 text-center space-y-4 max-w-xl mx-auto my-12 shadow-lg">
        <div className="w-12 h-12 bg-amber-100 dark:bg-amber-900/60 rounded-full flex items-center justify-center mx-auto text-amber-700 dark:text-amber-300 font-black text-xl">
          <Lock className="w-6 h-6" />
        </div>
        <div>
          <h2 className="text-base font-extrabold text-amber-900 dark:text-amber-200 uppercase tracking-wide">
            CO-Only Section — Restricted Access
          </h2>
          <p className="text-xs text-amber-800 dark:text-amber-300 mt-1 font-sans">
            Logged in as <strong>{currentUser.appointmentTitle}</strong>. System Backup & Restore, Disaster Recovery, and Cloud Storage exports are restricted strictly to the Commanding Officer (CO) and System Administrator.
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="bg-white dark:bg-slate-900 p-5 rounded-xl shadow-sm border border-slate-200 dark:border-slate-800 flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <Database className="w-5 h-5 text-[#2D4A22] dark:text-emerald-400" />
            <h2 className="text-base sm:text-lg font-bold text-slate-900 dark:text-white uppercase tracking-wide">
              {t('nav_backupRestore')} & Disaster Recovery (CO Exclusive)
            </h2>
            <span className="bg-[#D97706] text-black font-extrabold text-[10px] px-2 py-0.5 rounded uppercase">
              AES-GCM-256 ENCRYPTED
            </span>
          </div>
          <p className="text-xs text-slate-500 mt-0.5">
            Encrypted local offline backup generation, integrity verification & CO-authorized restore.
          </p>
        </div>

        {/* Sync status indicator */}
        <div className="flex items-center gap-2 bg-emerald-50 dark:bg-emerald-950/60 px-3 py-1.5 rounded-lg border border-emerald-200 dark:border-emerald-800 text-xs font-mono">
          <CheckCircle2 className="w-4 h-4 text-emerald-600 dark:text-emerald-400" />
          <div>
            <span className="font-bold text-emerald-800 dark:text-emerald-300 block">Cloud Sync Active</span>
            <span className="text-[10px] text-emerald-600 dark:text-emerald-400">Last Sync: {lastSyncTime}</span>
          </div>
        </div>
      </div>

      {/* Backup & Restore Action Panels */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Panel 1: Create Backup */}
        <div className="bg-white dark:bg-slate-900 p-5 rounded-xl border border-slate-200 dark:border-slate-800 shadow-sm space-y-4">
          <div className="flex items-center gap-2">
            <Lock className="w-5 h-5 text-[#2D4A22] dark:text-emerald-400" />
            <h3 className="font-bold text-sm text-slate-900 dark:text-white uppercase">
              Generate Encrypted Backup
            </h3>
          </div>
          <p className="text-xs text-slate-600 dark:text-slate-400">
            Packs all 17 system tables (Duty Rosters, Manpower, Vehicles, Medicine Batches, Instruments, Equipment, Approvals, Corrections, and Audit Logs) into an AES-256 encrypted payload.
          </p>

          <div>
            <label className="block text-xs font-bold text-slate-700 dark:text-slate-300 mb-1">
              Backup Encryption Passphrase
            </label>
            <input
              type="password"
              value={restorePassphrase}
              onChange={(e) => setRestorePassphrase(e.target.value)}
              className="w-full px-3 py-2 rounded-lg border border-slate-300 dark:border-slate-700 bg-slate-50 dark:bg-slate-800 text-xs font-mono"
            />
          </div>

          <button
            onClick={handleCreateBackup}
            disabled={isGenerating}
            className="w-full py-2.5 rounded-lg bg-[#2D4A22] hover:bg-[#3B5E2B] text-white font-bold text-xs shadow flex items-center justify-center gap-2 transition cursor-pointer"
          >
            <Download className="w-4 h-4" />
            <span>{isGenerating ? 'Encrypting & Packaging...' : t('action_createBackup')}</span>
          </button>
        </div>

        {/* Panel 2: Restore Backup */}
        <div className="bg-white dark:bg-slate-900 p-5 rounded-xl border border-slate-200 dark:border-slate-800 shadow-sm space-y-4">
          <div className="flex items-center gap-2">
            <Upload className="w-5 h-5 text-amber-600" />
            <h3 className="font-bold text-sm text-slate-900 dark:text-white uppercase">
              Restore System State
            </h3>
          </div>
          <p className="text-xs text-slate-600 dark:text-slate-400">
            Upload an authorized encrypted archive (.bak). Validates SHA-256 cryptographic checksum before restoring data.
          </p>

          <div>
            <label className="block text-xs font-bold text-slate-700 dark:text-slate-300 mb-1">
              Select Backup Archive File (.bak)
            </label>
            <input
              type="file"
              accept=".bak,.json"
              onChange={handleFileChange}
              className="w-full px-3 py-1.5 rounded-lg border border-slate-300 dark:border-slate-700 bg-slate-50 dark:bg-slate-800 text-xs"
            />
          </div>

          {restoreMessage && (
            <div className={`p-2.5 rounded-lg text-xs font-semibold ${restoreMessage.startsWith('SUCCESS') ? 'bg-emerald-100 text-emerald-900' : 'bg-red-100 text-red-900'}`}>
              {restoreMessage}
            </div>
          )}

          <button
            onClick={handleExecuteRestore}
            className="w-full py-2.5 rounded-lg bg-amber-600 hover:bg-amber-700 text-white font-bold text-xs shadow flex items-center justify-center gap-2 transition cursor-pointer"
          >
            <ShieldCheck className="w-4 h-4" />
            <span>Verify & Execute Restore</span>
          </button>
        </div>
      </div>

      {/* Cloud Storage & Scheduled Backup Info Section */}
      <div className="bg-white dark:bg-slate-900 p-5 rounded-xl border border-slate-200 dark:border-slate-800 shadow-sm space-y-3">
        <div className="flex items-center gap-2 border-b pb-2 border-slate-100 dark:border-slate-800">
          <ShieldCheck className="w-5 h-5 text-emerald-600" />
          <h3 className="font-bold text-sm text-slate-900 dark:text-white uppercase">
            Scheduled Cloud Firestore Backup & Storage Retention
          </h3>
        </div>

        <p className="text-xs text-slate-600 dark:text-slate-400">
          Cloud Firestore is configured for continuous real-time multi-region synchronization (`unit-ready-360`). Automated nightly backups are stored in Google Cloud Storage for long-term retention.
        </p>

        <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 pt-2 text-xs">
          <div className="p-3 rounded-lg bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700">
            <span className="font-bold text-slate-700 dark:text-slate-300 block">Realtime Snapshot Sync</span>
            <span className="text-[11px] text-emerald-600 dark:text-emerald-400 font-mono font-semibold">Active (`onSnapshot`)</span>
          </div>

          <div className="p-3 rounded-lg bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700">
            <span className="font-bold text-slate-700 dark:text-slate-300 block">Long-Term Bucket</span>
            <span className="text-[11px] text-slate-500 font-mono">gs://unit-ready-360.firebasestorage.app</span>
          </div>

          <div className="p-3 rounded-lg bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700">
            <span className="font-bold text-slate-700 dark:text-slate-300 block">Encryption Standard</span>
            <span className="text-[11px] text-slate-500 font-mono">AES-256 & SHA-256 HMAC</span>
          </div>
        </div>
      </div>
    </div>
  );
};
